# Generated by Django 4.1.7 on 2023-03-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pack",
            name="display_name",
            field=models.CharField(
                blank=True, help_text="显示名称（不填则使用名称）", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="pack",
            name="image",
            field=models.CharField(
                blank=True, help_text="图片名称（不填则使用名称）", max_length=40
            ),
        ),
    ]
