# Generated by Django 4.1.7 on 2023-04-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pack", "0002_pack_display_name_pack_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pack",
            name="on_sale",
        ),
        migrations.AddField(
            model_name="pack",
            name="end_date",
            field=models.DateField(blank=True, help_text="停售日期", null=True),
        ),
        migrations.AddField(
            model_name="pack",
            name="on_sale_control",
            field=models.CharField(
                choices=[
                    ("on", "manual on"),
                    ("off", "manual off"),
                    ("time", "control by time"),
                ],
                default="time",
                help_text="控制礼包是否在售",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pack",
            name="start_date",
            field=models.DateField(blank=True, help_text="开售日期", null=True),
        ),
    ]
